version: '3'
services:
  dataservice-publisher:
    build: .
    image: eu.gcr.io/digdir-fdk-infra/dataservice-publisher:test
    environment:
      - DATASERVICE_PUBLISHER_URL=${DATASERVICE_PUBLISHER_URL}
      - HOST_PORT=8080
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - FUSEKI_HOST_URL=http://fuseki:8080
      - FUSEKI_PASSWORD=${FUSEKI_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - "fuseki"

  fuseki:
      image: eu.gcr.io/digdir-fdk-infra/dataservice-publisher-sparql-service:staging_latest
      ports:
        - "3030:8080"
