version: '3'
services:
  dataservice-publisher:
    build: .
    image: eu.gcr.io/digdir-fdk-infra/dataservice-publisher:test
    environment:
      - DATASERVICE_PUBLISHER_URL=${DATASERVICE_PUBLISHER_URL}
      - DATASERVICE_PUBLISHER_PORT=8080
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - FUSEKI_HOST=http://fuseki
      - FUSEKI_PORT=8080
      - FUSEKI_PASSWORD=${FUSEKI_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
    ports:
      - "8000:8080"
    depends_on:
      - "fuseki"

  fuseki:
    image: eu.gcr.io/digdir-fdk-infra/dataservice-publisher-sparql-service:staging_latest
    ports:
      - "8080:8080"
