version: "3"
services:
  dataservice-publisher:
    build: .
    image: eu.gcr.io/digdir-fdk-infra/dataservice-publisher:test
    environment:
      - DATASERVICE_PUBLISHER_URL=${DATASERVICE_PUBLISHER_URL}
      - DATASERVICE_PUBLISHER_PORT=8080
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - FUSEKI_HOST=http://fuseki
      - FUSEKI_PORT=8080
      - FUSEKI_PASSWORD=${FUSEKI_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
    ports:
      - "8000:8080"
    depends_on:
      - "fuseki"

  fuseki:
    image: eu.gcr.io/digdir-fdk-infra/dataservice-publisher-sparql-service:staging_latest
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3.8.2-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 4s
      retries: 6
      start_period: 5s
