[tool.poetry]
authors = ["Stig B. Dørmænen <stigbd@gmail.com>"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
]
description = "A service for publishing dataservices in a datacatalog"
homepage = "https://github.com/Informasjonsforvaltning/dataservice-publisher"
license = "Apache-2.0"
name = "dataservice_publisher"
readme = "README.md"
repository = "https://github.com/Informasjonsforvaltning/dataservice-publisher"
version = "0.1.0"

[tool.poetry.dependencies]
PyJWT = "^2.4.0"
PyYAML = "^5.4.1"
SPARQLWrapper = "^2.0.0"
aiohttp = "^3.8.1"
aiohttp-middlewares = "^2.1.0"
content-negotiation = "^1.0.0"
gunicorn = "^20.0.4"
jsonpickle = "^2.0.0"
multidict = "^6.0.2"
oastodcat = "^2.0.1"
python = ">=3.8,<3.11"
python-dotenv = "^0.21.0"
python-json-logger = "*"
rdflib = "^6.0.0"
requests = "^2.25.1"

[tool.poetry.group.dev.dependencies]
Pygments = "^2.6.1"
Sphinx = "^5.1.1"
aiohttp-devtools = "^1.0.post0"
aioresponses = "^0.7.3"
black = "^22.6.0"
codecov = "^2.1.11"
coverage = "^6.4.4"
darglint = "^1.7.0"
docker-compose = "^1.28.6"
flake8 = "^5.0.4"
flake8-annotations = "^2.6.1"
flake8-assertive = "^2.1.0"
flake8-bandit = "^4.1.1"
flake8-black = "^0.3.3"
flake8-bugbear = "^22.7.1"
flake8-docstrings = "^1.6.0"
flake8-import-order = "^0.18.1"
mypy = "^0.971"
nox = "^2022.8.7"
nox-poetry = "^1.0.1"
pep8-naming = "^0.13.1"
pytest = "^7.1.2"
pytest-aiohttp = "^1.0.4"
pytest-asyncio = "^0.19.0"
pytest-cov = "^3.0.0"
pytest-docker = "^1.0.0"
pytest-dotenv = "^0.5.2"
pytest-mock = "^3.5.1"
pytype = "^2022.8.17"
requests-mock = "^1.8.0"
safety = "^2.1.1"
sphinx-autodoc-typehints = "^1.19.2"
types-PyYAML = "^6.0.11"
types-requests = "^2.28.8"
xdoctest = "^1.0.1"

[tool.coverage.paths]
source = ["dataservice_publisher", "*/site-packages"]

[tool.coverage.run]
omit = ["*gunicorn_config.py", "*content_negotiation.py"]
source = ["dataservice_publisher"]

[tool.coverage.report]
fail_under = 100
show_missing = true

[tool.mypy]
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true
strict = false
warn_unreachable = true

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = [
  "oastodcat.*",
  "datacatalogtordf.*",
  "pytest_mock.*",
  "requests_mock.*",
  "pythonjsonlogger.*",
  "gunicorn.*",
  "aioresponses.*",
  "content_negotiation.*",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
markers = [
  "unit: marks tests as unit (fast)",
  "integration: marks tests as integration (slower)",
  "contract: marks test as contract (slow)",
]

[build-system]
branch = false
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
