name: Deploy to production & demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy-production:
    name: Deploy to prod on merge to main branch
    uses: Informasjonsforvaltning/workflows/.github/workflows/build-deploy-nox.yaml@main
    with:
      app_name: dataservice-publisher
      python_version: '3.10'
      python_architecture: x64
      environment: prod
      cluster: digdir-fdk-prod
      nox_image: True
      nox_env: 4
      nox_env_1_name: SECRET_KEY
      nox_env_2_name: ADMIN_USERNAME
      nox_env_3_name: ADMIN_PASSWORD
      nox_env_4_name: FUSEKI_USERNAME
      run_safety: true
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GCP_SA_DIGDIR_FDK_GCR_KEY: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_KEY }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_PROD_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      NOX_ENV_1_VALUE: ${{ secrets.SECRET_KEY }}
      NOX_ENV_2_VALUE: ${{ secrets.ADMIN_USERNAME }}
      NOX_ENV_3_VALUE: ${{ secrets.ADMIN_PASSWORD }}
      NOX_ENV_4_VALUE: ${{ secrets.FUSEKI_PASSWORD }}

  deploy-to-demo:
    needs: build-and-deploy-production
    name: Deploy to demo if prod-deploy is successful
    uses: Informasjonsforvaltning/workflows/.github/workflows/deploy.yaml@main
    with:
      app_name: dataservice-publisher
      environment: demo
      cluster: digdir-fdk-dev
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
