name: Deploy to staging

on:
  pull_request:
    types: [ready_for_review, opened, reopened, synchronize]
    branches:
      - main

jobs:
  build-and-deploy-staging:
    name: Call reusable workflow when pull request is created
    if: github.event.pull_request.draft == false
    uses: Informasjonsforvaltning/workflows/.github/workflows/build-deploy-nox.yaml@chore/hos/debug
    with:
      app_name: dataservice-publisher
      python_version: '3.10'
      python_architecture: x64
      environment: staging
      cluster: digdir-fdk-dev
      nox_image: True
      nox_env: 4
      nox_env_1_name: SECRET_KEY
      nox_env_2_name: ADMIN_USERNAME
      nox_env_3_name: ADMIN_PASSWORD
      nox_env_4_name: FUSEKI_USERNAME
      run_safety: true
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GCP_SA_DIGDIR_FDK_GCR_KEY: ${{ secrets.GCP_SA_DIGDIR_FDK_GCR_KEY }}
      DIGDIR_FDK_AUTODEPLOY: ${{ secrets.DIGDIR_FDK_DEV_AUTODEPLOY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      NOX_ENV_1_VALUE: ${{ secrets.SECRET_KEY }}
      NOX_ENV_2_VALUE: ${{ secrets.ADMIN_USERNAME }}
      NOX_ENV_3_VALUE: ${{ secrets.ADMIN_PASSWORD }}
      NOX_ENV_4_VALUE: ${{ secrets.FUSEKI_PASSWORD }}
