name: Run tests

on:
  push:
    branches-ignore:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v1

     - name: Build Docker image
       run: docker build -t digdir/dataservice-publisher:latest .

     - name: Run Docker image
       run: docker run --env-file .env -p 8080:8080 -d digdir/dataservice-publisher:latest

     - name: Set up Python 3.7
       uses: actions/setup-python@v1
       with:
         python-version: 3.7

     - name: Test with pytest
       run: |
         pip install "poetry==1.0.5"
         poetry config virtualenvs.create false \
           && poetry install --no-dev --no-interaction --no-ansi
         pytest -rAs
