name: Run tests

on:
  push:
    branches-ignore:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Python 3.7
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
        architecture: x64
    - run: pip install nox==2019.11.9
    - run: pip install poetry==1.0.5
    - run: nox
